# Generated by Django 3.1.6 on 2022-01-01 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('desc', models.CharField(max_length=2000)),
                ('image1', models.FileField(upload_to='static/uploads')),
                ('catagory', models.CharField(choices=[('nature', 'nature'), ('travel', 'travel'), ('animal', 'animal')], max_length=20)),
            ],
        ),
    ]
