# Generated by Django 3.1.6 on 2022-01-03 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment_replycomment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='catagory',
        ),
    ]
