# Generated by Django 3.1.6 on 2022-01-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blog_catagory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='catagory',
            field=models.CharField(choices=[('nature', 'nature'), ('travel', 'travel'), ('animal', 'animal')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
