# Generated by Django 3.1.6 on 2022-01-03 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_likeblog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeblog',
            name='like',
            field=models.IntegerField(choices=[('like', 'like'), ('unlike', 'unlike')]),
        ),
    ]
