# Generated by Django 3.1.6 on 2022-01-03 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20220103_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likeblog',
            name='like',
            field=models.IntegerField(),
        ),
    ]
